### ISSUE TITLE
Replace userId FKs with username FKs

### ISSUE THREAD

**Issue by keyserj** [amelioro/ameliorate#217]
Want to replace topic.userId and userScore.userId with username as the FK. Need this for #191 

Motivation:
- want download/upload topic json to be human readable, e.g. with user scores by username rather than user id
- don't want to need extra logic to translate between userId and username
- prefer not to pass extra fields around on front-end (i.e. userId, since we want username everywhere)

Username as the FK shouldn't be a big deal because:
- username changes should be extremely rare - likely only to reserve a name for an endpoint, or to remove an offensive name
- username as FK can cascade update
- when username changes, downloaded topic json will go out of date, but json files should be re-downloadable with new username, and generally json files probably will be used soon after downloading
- when username changes, currently-open browsers' stores will go out of date, but api errors will prevent incorrect usernames from hurting anything in the api, and a page refresh will update usernames in the store to be correct

Created topic to convey reasoning for the decision https://ameliorate.app/keyserj/ameliorate-user-FKs

Need three PRs merged after another to avoid errors without downtime:
- [x] #218 merge one: add columns, start writing data (verify new topics and scores have username set)
- [x] #219 merge two: migrate data to new columns, require new column & replace FKs, start reading data (verify topics and scores still load)
- [ ] #220 merge three: remove old column writes, remove old columns (migrate after deploy) (verify existing topics and scores still load)
NOTE: made an oopsie - technically step 3 resulted in errors because old column writes were removed when the old column still existed with NOT NULL constraint. One possible better way could've been to remove the null requirement in step 2, then remove old column writes then could've been done there too, and step 3 would've just been remove old columns.
